export const FETCH_CISMATURITY_REQUEST = "FETCH_CISMATURITY_REQUEST"
export const FETCH_CISMATURITY_SUCCESS = "FETCH_CISMATURITY_SUCCESS"
export const FETCH_CISMATURITY_FAILURE = "FETCH_CISMATURITY_FAILURE"